### PR TITLE
management > managers

### PR DESCRIPTION
**Pull request by MirjamvT**
more grammatically in line with policy makers and designers, developers.
also: i would like to specify what these managers are managing. we are not talking about the local grocery store manager!

### CODE REVIEW

**Comment by MirjamvT** [comment]
does that mean you suggest i make an issue for this suggestion?

**Comment by bvhme** [comment]
@MirjamvT, I'd say yes, make an issue since this is not something that you I think can easily change everywhere right now. It needs project wide find-and-replace.

**Comment by MirjamvT** [comment]
done!

Best regards,
Mirjam van Tiel
+31 6 4662 8454

 Come work with us! <https://about.publiccode.net/roles/>

**Comment by ElenaFdR** [comment]
This is captured in #213, so I'm closing this PR.

**Pull request closed without merging**
