### PR TITLE
Clarify possible SHOULD exception for multiple parties

### PR DESCRIPTION
**Pull request by ericherman**
See also:
https://github.com/publiccodenet/standard/issues/946

### CODE REVIEW

**Review by Ainali — APPROVED** [review]
I like this, it makes the intention clear.

**Comment by ericherman** [comment]
This doesn't address very mature codebases and it repeats itself.
I would like to reduce the duplication before making it more verbose, but I do not have a strong idea of how to do that yet.

**Comment by ericherman** [comment]
Based on the conversation yesterday with @jan, I've altered the branch. I'm still not "in love" with it.

**Comment by jan** [comment]
@ericherman I'm sad to learn you are not in love with me.

**Comment by ericherman** [comment]
> @ericherman I'm sad to learn you are not in love with me.

I'm sorry for the spam @jan! I meant to tag @Ainali -- I'll try to be more careful.

**Review by Ainali — APPROVED** [review]

**Pull request merged**
