### PR TITLE
Add 'Use continuous delivery' guide

### LINKED ISSUE #26: Tests and CI: add all fields
• Measure
• What this does
• What this doesn’t do
• How to test
• Policy makers: what you need to do
• Management: what you need to do
• Developers and designers: what you need to do
• Further reading

### PR DESCRIPTION
**Pull request by bvhme**
Hey @ElenaFdR, I couldn't find any contents in your branch, but this is my suggestion. Feel free to edit and merge when good, or give feedback and let me edit.

Fixes #26

### CODE REVIEW

**Comment by ElenaFdR** [comment]
This looks good. Not sure why mine isn't showing up, but I'll add non-duplicate content to this branch and then delete my branch.

**Comment by ElenaFdR** [comment]
> This looks good. Not sure why mine isn't showing up, but I'll add non-duplicate content to this branch and then delete my branch.

Looks like I made an incorrect assumption that I could switch between branches on GitHub Desktop and push commits from one file to only one branch while retaining my work in Atom; frustratingly, my work seems to be gone now.

**Comment by ElenaFdR** [comment]
Found it!

**Comment by bvhme** [comment]
Great!

Also, it is often not about the things you wrote down but what you've gone
through in your brain, writing it again often leads to better results :)

**Comment by bvhme** [comment]
And, feel free to merge this one :) when ready

**Pull request merged**
