### PR TITLE
Remove redundant open standard definitions

### PR DESCRIPTION
**Pull request by Ainali**
It's already well defined in the glossary and we don't need
to repeat that several times.

-----
[View rendered criteria/open-standards.md](https://github.com/publiccodenet/standard/blob/ja-remove-redundant-definition/criteria/open-standards.md)

### CODE REVIEW

**Review by ericherman — APPROVED** [review]

**Comment by bvhme** [comment]
I would have actually done this the other way around. The Open Standard Definition from the Open Source Initiative effectively is a part of this requirement, now it requires one to find that context in the glossary. I think we don't use open standards a lot elsewhere so I think it might not be necessary to have this in the glossary.

**Comment by ericherman** [comment]
I think @bvhme makes a strong point, we only use it in two criteria:
```
 git grep -il 'opensource.org\|Open Standard'
criteria/open-licenses.md
criteria/open-standards.md
glossary.md
index.md
```

And in those two criteria, there may not be enough overlap to make the indirection of the glossary worth it:
```
$ git grep -i 'opensource.org\|Open Standard'
criteria/open-licenses.md:* Software source code MUST be licensed under an [OSI-approved open source license](https://opensource.org/licenses/category).
criteria/open-licenses.md:* The license for the source code is on the [OSI-approved Open Source license list](https://opensource.org/licenses/category) and the license for documentation is [conformant to the Open Definition](https://opendefinition.org/licenses/).
criteria/open-licenses.md:* [Open source definition](https://opensource.org/osd) by the Open Source Initiative - all open source licenses meet this definition.
criteria/open-standards.md:# Use open standards
criteria/open-standards.md:* For features of a codebase that facilitate the exchange of data the codebase MUST use an open standard.
criteria/open-standards.md:* If no existing open standard is available, effort SHOULD be put into developing one.
criteria/open-standards.md:* Functionality using features from a standard that is not an open standard MAY be provided if necessary, but only in addition to compliant features.
criteria/open-standards.md:* Prohibit procurement of technology that does not use open standards.
criteria/open-standards.md:* Consider including open standard compliance assessment in code reviews.
criteria/open-standards.md:* [Open Standard Requirements](https://opensource.org/osr) by the Open Source Initiative.
glossary.md:Open source is defined by the Open Source Initiative in their [Open Source Definition](https://opensource.org/osd-annotated).
glossary.md:## Open standard
glossary.md:An open standard is any standard that meets the Open Source Initiative's [Open Standard Requirements](https://opensource.org/osr).
index.md:  * [Use open standards](criteria/open-standards.md)
```
If we in-line, how much duplication are we talking about? @Ainali what do you think?

**Comment by Ainali** [comment]
To me, it doesn't really matter which solution we make, either way works for me. I just believed that the glossary was preferred since energy already went into creating that definition even with this few mentions. If you think you can make a more elegant solution @bvhme I would be happy to review it!

**Comment by ElenaFdR** [comment]
Folks, there are no hyperlinks in this now to either our glossary definition or the OSI definition. This change seems actively unhelpful to someone wondering what we consider an open standardl

**Comment by Ainali** [comment]
> Folks, there are no hyperlinks in this now to either our glossary definition or the OSI definition. This change seems actively unhelpful to someone wondering what we consider an open standardl

No, it's still in the bottom of the page.

**Comment by ericherman** [comment]
In `develop` (at the time of this writing), the glossary section (which comes before the criteria), the "Open standard" entry contains the link. The link is repeated in the "Open Standard Requirements by the Open Source Initiative." of the "Further reading".

Perhaps it would be best to remove the "Further reading" from this criterion in favor of in-lining the sole bullet in to the requirement.

**Comment by ElenaFdR** [comment]
@ainali This obscures /our/ endorsement of this open standard definition - you can infer it, but you have to seek out the glossary to find confirmation (or read the website linearly, which #217 makes harder to do.)
I like @bvhme and @ericherman's solutions.
(Hurrah for deleting unnecessary content!)

**Pull request merged**
