### PR TITLE
Rephrase Document Objectives to highlight policy objectives

### PR DESCRIPTION
**Pull request by ericherman**
Rather than phrase the requirement in terms of "understandable by policy
makers", this phrasing connects the codebase goals to policy goals.

See also issue #62 

-----
[View rendered criteria/document-objectives.md](https://github.com/ericherman/standard-for-public-code/blob/policy-objectives-20210614/criteria/document-objectives.md)

### CODE REVIEW

**Review by Ainali — APPROVED** [review]
Nice! I think this better capture what we want to have documented, the clear line from the public policy to the code.

**Comment by ericherman** [comment]
I suggest that whatever the wording, it must acknowledge that not all policy objectives are reflected in codebase, and similarly not all codebase objectives are going to be clear reflections of policy.

With that in mind, would wording similar to:

`Codebase documentation SHOULD clearly describe how policy objectives and codebase objectives are reflections of each other or connected.`

have lower "wedge" risk?

**Comment by Ainali** [comment]
> The intent here, in my understanding, is to say that developers need to be able to describe what their code does to people who write code in a different language (policy makers) who are dependent on the code.

If this was the intent, perhaps we should keep this requirement (but making it clearer to make that intent clear)? 
What we tried to address was to make connection between the objectives of a policy (example: "The city should be a pleasant place for bikers and pedestrians") and a codebase objective (example: "The image algorithms should discover all cars parked on a bike lane or footpath"). The policy in itself have no objective of discovering cars, but how the codebase works is totally dependent on it.

**Comment by bvhme** [comment]
I think you are right @Ainali, the challenge is indeed on how it is phrased in a way that the one is not excluding, since it is a bit grey-area all around.

In your example, the algorithm is also a form of policy, namely a computer run execution policy in service of a more abstract policy.

I suspect we need to create the space for the entire stack of abstractions of code to be documented instead of splitting them in the highest (laws/resolutions) and lowest level form (execution policy and software) without the intermediate levels.

**Review by felixfaassen — APPROVED** [review]

**Comment by ericherman** [comment]
Would something like this be better?

```
The codebase SHOULD contain clear documentation of its objectives. Where applicable, codebase objectives should be expressed in terms of policy objectives.
 ```

**Comment by Ainali** [comment]
> Would something like this be better?
> 
> ```
> The codebase SHOULD contain clear documentation of its objectives. Where applicable, codebase objectives should be expressed in terms of policy objectives.
> ```

I don't know, this feels a bit mysterious to me and I am not really sure what it means. I guess what we want, but perhaps in a not so wordy phrasing is something like this:

```
The codebase SHOULD contain clear documentation of its objectives.
Especially, the documentation should explain how the codebase aims to solve the objectives of the public policies causing the creation of it.
```

**Review by ElenaFdR — APPROVED** [review]
Clear enough; I look forward to seeing how people act on it.

**Pull request merged**
