### PR TITLE
Require high level architectural documentation

### PR DESCRIPTION
**Pull request by ericherman**
This need was raised in discussion in PR #606 by @jgroenen

-----
[View rendered criteria/documenting.md](https://github.com/ericherman/standard-for-public-code/blob/document-components/criteria/documenting.md)

### CODE REVIEW

**Comment by kerkuil** [comment]
Architecture was something we already discussed in preparation of https://github.com/publiccodenet/standard/pull/573. The PR is what we settled with.

**Comment by kerkuil** [comment]
```diff
+ The documentation SHOULD describe the key components and modules of the codebase and their relationships, for example as a high level architectural diagram.
- The documentation SHOULD describe the key components or modules of the codebase and their relationships, for example as a high level architectural diagram.
```

We've discussed before that modules are technical implementations of modules. That would imply that you can't have modules without first defining components.

**Comment by ericherman** [comment]
> We've discussed before that modules are technical implementations of modules. That would imply that you can't have modules without first defining components.

I see value in allowing a high level architectural diagram to be at the resolution most useful for contributors to that codebase.
I would expect a codebase which is library to have its high-level documentation differently "zoomed out" than the diagram of a web app.

**Comment by kerkuil** [comment]
I didn't argue on the high-level documentation. I argued that you can't have modules without having components defined first.

**Pull request merged**
