### PR TITLE
Code coverage devs do

### PR DESCRIPTION
**Pull request by ericherman**
plugability for corner-case testing, and tuning code coverage tooling

### CODE REVIEW

**Comment by ericherman** [comment]
>     1. The first bullet point is a very long nested sentence with double "which" and "such". Can it perhaps be split up into two sentences to make it easier to grasp?

What about this wording?

* Structure code which is written to handle conditions which are difficult to create in a test environment in such a way that the conditions can be simulated during testing. Forms of resource exhaustion such as running out of storage space or memory allocation failure are typical examples of difficult to create conditions.

**Comment by Ainali** [comment]
Yes, that would be a lot easier to read!

**Comment by ericherman** [comment]
or maybe:

* Structure code written to handle conditions which are difficult to create in a test environment in such a way that the conditions can be simulated during testing. Forms of resource exhaustion such as running out of storage space and memory allocation failure are typical examples of difficult to create conditions.

**Comment by Ainali** [comment]
> or maybe:
> 
> * Structure code written to handle conditions which are difficult to create in a test environment in such a way that the conditions can be simulated during testing. Forms of resource exhaustion such as running out of storage space and memory allocation failure are typical examples of difficult to create conditions.

Even better!

**Pull request merged**
