### PR TITLE
make this sentence an 'active one' too

### PR DESCRIPTION
**Pull request by MirjamvT**

### CODE REVIEW

**Comment by bvhme** [comment]
The test here is to make sure that a version is published on the internet, not to publish it. It is an outcome statement that tests for 'if you look at where it should be it is there'

**Comment by MirjamvT** [comment]
this 'how to test' header (not a question, though in question form, grammatically) is still puzzling to me. it does not seem to intuitively match the sentence below.
how about turning the text below into a question ('is the code...'), a 'yes' answer would then be a 'pass' on the test.

**Comment by bvhme** [comment]
I think that is a great idea, however that should be an issue and not a Pull Request :)

Would you like to add it or shall I?

**Comment by MirjamvT** [comment]
After reading the intro (wasn't avaible at the time i made this PR i think) I understand 'How to test' to mean 'How to test if a contribution is compliant with this standard'.
will make a pull request for making the header readable 'on its own' (and longer, regrettably)

**Pull request closed without merging**
