### PR TITLE
Eh check only new links

### PR DESCRIPTION
**Pull request by ericherman**
Here a rough starting point for checking new links.

TODO: At the time of this rough draft, it does not yet have a url-ignore feature, but I'd like to get some early feedback on the idea.

### CODE REVIEW

**Comment by Ainali** [comment]
I tried it and did a small change and got this result, which we perhaps should handle:

```
./script/check-new-links.sh 
https://help.github.com/articles/creating-an-issue/
HTTP/2 301 
FAIL: 1 new URLs were not OK
```

**Comment by ericherman** [comment]
Perhaps. I'd like newly added links should not reference "moved permanently" old locations, thus I'm on the fence about this one.

**Comment by Ainali** [comment]
That is a very good point and I think I agree with it in general, but doesn't that mean that some short URLs cannot be added?
I am not saying it is a blocker of any kind, just making sure we are making these decisions consciously.

**Comment by ericherman** [comment]
@Ainali Your question raises a solid point ... perhaps "moved permanently" should maybe warn, but should not fail if the resource is there. Please try with this new addition.

**Review by Ainali — APPROVED** [review]
This is really cool and will be very helpful!

**Comment by ericherman** [comment]
Okay, good. Thus the next step is to add a way to ignore urls. I'll sketch that out next.

**Comment by ericherman** [comment]
> As a sidenote this example also shows why I (and we) should use new line more often, because the failing URL was not part of my change, but since the paragraph is long, it _is_ part of the diff.

Yes.
I think we can all be better about putting in newlines after every period.

**Comment by ericherman** [comment]
Okay, URL ignore via regular expression added. @Ainali what do you think now?

**Review by Ainali — APPROVED** [review]
I tried a few different test cases and it works fine!

**Review by felixfaassen — APPROVED** [review]

**Pull request merged**
