### PR TITLE
Editorial/readers guide

### PR DESCRIPTION
**Pull request by fliepeltje**
See issue #949

### CODE REVIEW

**Comment by ericherman** [comment]
Hello @fliepeltje, the idea to convert headings to bullet points is one worthy of consideration. I can see a correctness angle that the items are perhaps not sub-sections themselves. I also see that it changes the presentation such that it no longer carries the visual theme of the criteria layout. I'll raise this to the other foundation staff and collect opinions.

**Comment by ElenaFdR** [comment]
Hi @fliepeltje, thanks for thinking with us on the layout and clarity. 

What was your logic for changing the content under each subheading? We tried to make the overall tone quite friendly, and the role explanations respectful and easy to understand by mentioning example responsibilties. It looks like you've changed this to listing areas of responsibility and cut out all the chattiness?

I don't think that changing subheadings to bullets increases usability. This is because:

- nested bullets are hard to read; we usually try to rewrite content to avoid them
- on a full page of bullets, it's often harder to keep track of the context of bullets further away from the introduction
- changing the sections being defined from subheadings to bolded text behind a bullet makes it harder for someone to skim to find the right section if they're looking for specific information. Screenreaders also let people skip from subheading to subheading, while treating bolded text quite variably (with the result that accessibility guidelines recommend against using bold for emphasis)

I think the correct comparison for this page's structure is the glossary, where a term or concept is defined, rather than a long list.

**Comment by fliepeltje** [comment]
So as someone who wants to implement this, I am thinking very much from the perspective of someone who is reading this document with the idea to extract the relevant information and apply it. In that role, I expect this to be more of technical manual and in that regard I value briefness over chattiness which is the core motivation to reduce the amount of content. 

Personally, I find subheadings can be distracting, but I am aware that this is subjective. The reason I dislike them is that they prolong the file just in terms of height. It's like spreading your content over 2 A4s when it can fit on a post-it note. As someone who just wants to know what to do here, I want the information quickly. 

I should note, this type of structure to me only makes sense for this chapter; it is not something I would like to extend to other documents too. I indeed like the ability to send hrefs to specific subsections to colleagues and from the point of view of accessibility, it is nicer and it is a structure I would keep. But for this section it makes no sense to me. 

As a more concrete example, consider this section:

> ## Developers and designers: what you need to do
>
> This section tries to specifically speak to developers and designers by offering them concrete actions they can perform in  their role.
> 
> Developers are usually more technically aligned and have more impact on the delivery of services than the previous groups.

The paragraphs below add very little information, but take up a lot of space and are not as easy to scan as some bullet points. 

I guess in the bottom line I'd just like the standard to be a bit shorter and to-the-point in terms of writing really focusing very hard on whether the content adds information or is more filler text. At the same time, I think some levity in a document is nice too, but I would rather see that though examples and anecdotes, but not mixed with the technical specifications.

**Comment by ericherman** [comment]
Given that the current layout targets the [pdf version](https://github.com/publiccodenet/standard/releases/download/0.7.0/standard-for-public-code-0.7.0.pdf) we are likely to keep that format.

The text could be tightened up, if it is consistent with that format. Some of the text-shortening in this patch is achieved by converting full sentences to shorter bullet phrases, which would not be consistent with the format. That said, making the sentences shorter and sharper would be welcome.

**Comment by fliepeltje** [comment]
Alright; I'll see if I can feed some more contributions like that when I find the time for it :)

**Pull request closed without merging**
