### PR TITLE
Sign commits and provide an email address

### LINKED ISSUE #146: Requirement for version control, commit with an email adress
This so that future contributors are able to contact past contributors with questions about their work. This can be a special purpose pseudonimed email adress.

### PR DESCRIPTION
**Pull request by maukoquiroga**
Fixes #146

-----
[View rendered criteria/version-control-and-history.md](https://github.com/maukoquiroga/standard/blob/patch-1/criteria/version-control-and-history.md)

### CODE REVIEW

**Review by ericherman — CHANGES_REQUESTED** [review]
This is good.

tiny nit-pick: I think we wish contributors to provide an email _address_, not an email.

**Review by ericherman — APPROVED** [review]

**Review by felixfaassen — APPROVED** [review]

**Review by raboof — APPROVED** [review]
I like it. Perhaps it should even be 2 bullets, since they're somewhat separate concerns, but this is :+1: already

**Review by ElenaFdR — APPROVED** [review]
Nice work!

**Comment by ElenaFdR** [comment]
Both links flagged by Travis work in a browser.

**Comment by ericherman** [comment]
@maukoquiroga How would you like to be listed in https://github.com/publiccodenet/standard/blob/develop/AUTHORS.md ?

**Comment by maukoquiroga** [comment]
@ericherman For now, Individual contributor is ok.

**Pull request merged**
