### PR TITLE
Less focus on contributor behavior

### LINKED ISSUE #846: Many requirements say "contributors SHOULD" or similar - review for better wording
Rather than talk about what people do, we can talk about what expectations are described in the codebase documentation. 

For instance, as a contributor I might initially not group relevant commits together, in this case, a maintainer may decide to do the re-grouping as a part of their work in shepherding the patch into the main development branch rather than pedantically enforce that I, the contributor, must be the one to fix the patch.

### PR DESCRIPTION
**Pull request by ericherman**
fixes #846

### CODE REVIEW

**Comment by Ainali** [comment]
This is really an improvement!

I wonder if the "Contribution review MUST verify that no sensitive information is being contributed." could be rephrased so that it doesn't focus on the review itself, as we almost need to be there and see it to verify.
Is it too roundabout to also talk about guidelines here?

**Comment by ericherman** [comment]
I had a very similar thought, but in other places we talk about reviewers, too.

Maybe we can be prescriptive about reviewer behaviour, but I lean in the direction of thinking we should talk about review policy/guidelines as well.

**Comment by ericherman** [comment]
I compromised with "review must include" as being non-specific about which reviewer does what, but that somewhere along the process it happens. I'm not sure it's a clear enough compromise.

**Review by Ainali — APPROVED** [review]

**Comment by Ainali** [comment]
We can perhaps improve it even further later on, but just as it is, it is still better than what we have.

**Comment by ericherman** [comment]
Okay, I propose we let's let this sit a couple of days at least; maybe we will have more ideas or get more input.

**Comment by Ainali** [comment]
Thinking about it, since the first of the requirements says, "MUST NOT contain" it is really implied that it has to be reviewed for it because if such things are merged, the first requirement fails. So perhaps the requirement about the review is not really needed.

**Review by Ainali — APPROVED** [review]

**Pull request merged**
