### PR TITLE
Expand Bundle policy and code to clearly include processes

### PR DESCRIPTION
**Pull request by ericherman**
See issue #568

Co-authored-by: Jan Ainali

-----
[View rendered criteria/bundle-policy-and-code.md](https://github.com/ericherman/standard-for-public-code/blob/bundle-policy-code-expand-20220203/criteria/bundle-policy-and-code.md)

### CODE REVIEW

**Comment by kerkuil** [comment]
I think it would be valueable if *part of* a codebase and *part of* a solution is defined somewhere in general. E.g.:"
```
Wherever we speak of codebase or solution we also mean parts of a codebase or part of a solution.
```

**Comment by kerkuil** [comment]
```diff
  Gemeente Amsterdam

  * Tamas Erkelens
  * Mark van der Net
  * Maurits van der Schee
+ * Maurice Hendriks
```

**Review by Ainali — APPROVED** [review]

**Comment by Ainali** [comment]
The latest changes was a result of the [backlog pruning session last Thursday](https://blog.publiccode.net/community%20call/2022/03/11/pruning-the-oldest-issues.html).

**Comment by Ainali** [comment]
> I think it would be valueable if _part of_ a codebase and _part of_ a solution is defined somewhere in general. E.g.:"
> 
> ```
> Wherever we speak of codebase or solution we also mean parts of a codebase or part of a solution.
> ```

This is perhaps out of scope of this pull request, we tried to address it in #567 (that changes Create portable and reusable code) where we think it is really fitting.

**Review by Ainali — APPROVED** [review]

**Comment by kerkuil** [comment]
> > I think it would be valueable if _part of_ a codebase and _part of_ a solution is defined somewhere in general. E.g.:"
> > ```
> > Wherever we speak of codebase or solution we also mean parts of a codebase or part of a solution.
> > ```
> 
> This is perhaps out of scope of this pull request, we tried to address it in #567 (that changes Create portable and reusable code) where we think it is really fitting.

True

**Pull request merged**
