### PR TITLE
Add the "Draft" back to the version info on cover

### PR DESCRIPTION
**Pull request by ericherman**
fixes #660

### CODE REVIEW

**Comment by Ainali** [comment]
This looks good on print.html, but on the PDFs the word 'Draft' is not turning into bold text when I generate them.

**Comment by ericherman** [comment]
> This looks good on print.html, but on the PDFs the word 'Draft' is not turning into bold text when I generate them.

That is very strange because it renders bold for me; let's screen share and see if we can figure our what's different.

**Comment by Ainali** [comment]
Yeah, the html's look fine, but I have WeasyPrint version 54.1, so that is probably it.

**Review by Ainali — APPROVED** [review]
Proven to work with the right setup, we should probably always do a visual check when generating PDFs to catch possible WeasyPrint oddities.

**Pull request merged**
