### PR TITLE
Start refactoring the introduction

### PR DESCRIPTION
**Pull request by Ainali**
This pull request is intentionally bold to get our discussion more concrete. Even though suggestions of changes to pull requests are always welcome, in this one they are especially appreciated.

Since some texts may fit better elsewhere, I removed:
- Why public code?
- How public code works

I moved the section with the goals ahead of the section with certification process, since that is more of an overview, especially with the other text gone.

I also removed the Further reading, which was more of a further reading of public code than the Standard. I think we do want *some* Further reading later, but it should be content more related to the Standard.

Works towards #425. 

-----
[View rendered index.md](https://github.com/publiccodenet/standard/blob/ja-intro-refactoring/index.md)
[View rendered introduction.md](https://github.com/publiccodenet/standard/blob/ja-intro-refactoring/introduction.md)

### CODE REVIEW

**Comment by ericherman** [comment]
I like the essence of this.

As was discussed in #425 and related community calls, the cut material is probably best suited outside.
Before merging this, would we like to see that content ported to the new location?
Or would we want to have this first and then re-create the related content elsewhere with our current understanding as a follow-on?

**Comment by Ainali** [comment]
I think it would be wise to at least have a plan where it should go before we remove it. A short gap is probably not that bad, but if it turns into a longer period, it is a considerable amount of good background information that we are missing.

**Review by ericherman — APPROVED** [review]

**Comment by ericherman** [comment]
Reviewing issue #218 makes me think that even the description of certification belongs outside the text of the standard and would fit better on publiccode.net

**Comment by Ainali** [comment]
I suggest we have this pull request as a topic for the community call on Thursday, October 7.

**Comment by nicorikken** [comment]
It saddens me to see the references to the larger context of Public Code and the reference to the Public Money? Public Code! campaign gone. Indeed this is a bold pull-request, and I can see this as the Standard for Public Code growing up and no longer needing these references in the standard. So I can see it in a positive light. As suggested by @ericherman I can see a place for this context on the website. I hope the Foundation for Public Code will keep explaining the values of Public Code and proven methods (to newcomers). As it is in the interest of the Foundation for Public Code to do so, I'm sure you will.

**Comment by ericherman** [comment]
@nicorikken The content shouldn't be going away, rather moved from inside the Standard's introduction to on the publiccode.net websites. Outside of the intro, I expect this content to be expanded to suit multiple readers. I expect we won't even see this removal merged until similar material is merged elsewhere.

**Review by nebster — CHANGES_REQUESTED** [review]
this definitely requires further thought about how much context about our work we can deliver with the standard.

**Comment by Ainali** [comment]
Yes, I suggest that we close the pull request for now and start with something new when we have had time to come up with new ideas.

**Comment by Ainali** [comment]
I had forgotten to link to the notes from the community call when this pull request were discussed: https://blog.publiccode.net/community%20call/2021/10/11/notes-from-community-call-7-october-2021.html

**Comment by Ainali** [comment]
Closing this pull request for now as we have chosen a different direction and any work needed for that can start from a fresh branch.

**Pull request closed without merging**
